config/routes.rb
ChemicalInventorySystem::Application.routes.draw do
  resources :chemicals do
    resources :uses, :recurring_uses
  end

  get "home/index"

  root :to => 'chemicals#index'

end

app/models/chemical.rb
class Chemical < ActiveRecord::Base
  attr_accessible :amount, :cas, :name
  has_many :uses
  has_many :recurring_uses 
  
  validates :name,   :presence => true
  validates :amount, :presence => true,
                     :numericality => { :greater_than_or_equal_to => 0 }
  validates_uniqueness_of :cas, :allow_blank => true, :allow_nil => true
  validate :cas_must_be_valid
  
  before_validation :pre_validation_process
  
  def pre_validation_process
    if self.cas != nil
      self.cas = self.cas.strip
      if self.cas.length == 0
        self.cas = nil
      end
    end
  end
  
  def cas_must_be_valid
    if self.cas != nil and not self.class.validate_cas(self.cas)
      errors.add(:cas, "is not valid")
    end
  end
  
  def cas_link
    "http://www.commonchemistry.org/ChemicalDetail.aspx?ref=" + cas
  end
  
  def self.validate_cas(cas_number)
    match = /^(\d{2,7})\-(\d{2})\-(\d)$/.match(cas_number)
    if not match
      return false
    end
    
    seq = match[1] + match[2]
    digits = seq.split('').map{ |ch| ch.to_i }
    
    n = digits.size
    sum = 0
    digits.each do |d|
      sum += d*n
      n -= 1
    end
    
    r = match[3].to_i
    return r == sum % 10
  end
  
  def to_s
    "Chemical: #{self.name}--#{self.cas} (#{self.amount})"
  end
  
  # To get actual inventory amount, consider recuring usages on top of the
  # number stored in database.
  # For each scheduled recurring use on this chemical,
  # calculate the amount that was supposed to have been consumed between
  # first effective date and the calculate date. 
  # @param calculate_date: date object
  def calculate_actual_amount(calculate_date = nil, allow_negative = false)   
    if calculate_date.nil?
      calculate_date = Time.now.to_date
    end
    
    total_deduct = 0
    self.recurring_uses.each do |ru|
      total_deduct += ru.cumulated_consumption(calculate_date)
    end
    actual_amount = self.amount - total_deduct
    return (allow_negative || actual_amount > 0) ? actual_amount : 0
  end
  
  def days_til_ran_out(calculate_date)
    remaining = self.calculate_actual_amount(calculate_date, true)
    if remaining < 0
      return -1 # ran out already
    elsif remaining == 0
      if self.recurring_usage_on(calculate_date) > 0
        return 0 # ran out on this day
      else
        return -1 # ran out before this day
      end
    end
    
    if !self.recurring_uses.any?
      return -2 # never gonna hit shortage
    end
    
    # get scheduled recurring uses
    i = 0
    to_check = {}
    self.recurring_uses.each do |ru|
      to_check[i] = ru
      i += 1
    end

    last_valid_consumption = nil # most recent date with a valid consumption 
    date = calculate_date # date for iteration
    to_remove = nil
    
    # do calculations day by day until we hit shortage or we have no more
    # active recurring use
    while remaining > 0 && to_check.any?
      date += 1
      
      # check schedules regarding the next day's deduction
      deduction = 0
      to_check.each do |i, ru|
        if date < ru.first_effective_date
          # not activated yet, skip
        elsif !ru.end_date.nil? && date > ru.end_date
          # inactive, need to remove this
          if to_remove.nil?
            to_remove = []
          end
          to_remove << i
        else
          # active recurring use, add deduction for this day
          deduction += ru.consumption_on(date)
        end
      end
      
      if deduction > 0
        remaining -= deduction
        if remaining >= 0
          last_valid_consumption = date
        end
      end
      
      # remove inactive recurring use
      if !to_remove.nil?
        to_remove.each do |i|
          to_check.delete(i)
        end
        to_remove = nil
      end
    end
    
    if remaining > 0
      return -2 # never gonna ran out
    elsif last_valid_consumption.nil?
      return -1 # no valid consumption after given calculate date
    else
      return (last_valid_consumption - calculate_date).to_i
    end
  end

  def ran_out_date_s(calculate_date=nil)
    if calculate_date.nil?
      calculate_date = Time.now.to_date
    end
    
    days = self.days_til_ran_out(calculate_date)
    if days >= 0
      return (calculate_date + days).to_s
    elsif days == -2
      return "not exists"
    elsif days == -1
      return "already in shortage"
    else
      return "n/a"
    end
  end
  
  def recurring_usage_on(date)
    consumption = 0
    self.recurring_uses.each do |ru|
      consumption += ru.consumption_on(date)
    end
    return consumption
  end
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  # GET /chemicals
  # GET /chemicals.json
  def index
    @chemicals = Chemical.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @chemicals }
    end
  end

  # GET /chemicals/1
  # GET /chemicals/1.json
  def show
    @chemical = Chemical.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @chemical }
    end
  end

  # GET /chemicals/new
  # GET /chemicals/new.json
  def new
    @chemical = Chemical.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @chemical }
    end
  end

  # GET /chemicals/1/edit
  def edit
    @chemical = Chemical.find(params[:id])
  end

  # POST /chemicals
  # POST /chemicals.json
  def create
    @chemical = Chemical.new(params[:chemical])

    respond_to do |format|
      if @chemical.save
        format.html { redirect_to @chemical, :notice => 'Chemical was successfully created.' }
        format.json { render :json => @chemical, :status => :created, :location => @chemical }
      else
        format.html { render :action => "new" }
        format.json { render :json => @chemical.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chemicals/1
  # PUT /chemicals/1.json
  def update
    @chemical = Chemical.find(params[:id])

    respond_to do |format|
      if @chemical.update_attributes(params[:chemical])
        format.html { redirect_to @chemical, :notice => 'Chemical was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @chemical.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chemicals/1
  # DELETE /chemicals/1.json
  def destroy
    @chemical = Chemical.find(params[:id])
    @chemical.destroy

    respond_to do |format|
      format.html { redirect_to chemicals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/views/chemicals/_form.html.erb
<%= form_for(@chemical) do |f| %>
  <% if @chemical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chemical.errors.count, "error") %> prohibited this chemical from being saved:</h2>

      <ul>
      <% @chemical.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :cas, "CAS" %><br />
    <%= f.text_field :cas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chemicals/edit.html.erb
<h1>Editing chemical</h1>

<%= render 'form' %>

<%= link_to 'Show', @chemical %> |
<%= link_to 'Back', chemicals_path %>

app/views/chemicals/index.html.erb
<h1>Chemical Inventories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>CAS</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chemicals.each do |chemical| %>
  <tr>
    <td><%= chemical.name %></td>
    <td><%= chemical.calculate_actual_amount %></td>
    <td>
      <% if chemical.cas.to_s != '' %>
	  	<%= link_to chemical.cas, chemical.cas_link %>
		  <% end %>
    </td>
    <td><%= link_to 'Show', chemical %></td>
    <td><%= link_to 'Edit', edit_chemical_path(chemical) %></td>
    <td><%= link_to 'Remove', chemical, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chemical', new_chemical_path %>

app/views/chemicals/new.html.erb
<h1>New chemical</h1>

<%= render 'form' %>

<%= link_to 'Back', chemicals_path %>

app/views/chemicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chemical.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @chemical.calculate_actual_amount %>
</p>

<p>
  <b>CAS:</b>
  <%= @chemical.cas %>
</p>

<p>
  <b>Forecast Run Out Date:</b>
  <%= @chemical.ran_out_date_s %>
</p>

<h2>One Time Uses:</h2>
<table>
	<tr>
    <th>Chemist</td>
    <th>Amount</td>
    <th>Record Time</td>
  </tr>
<% @chemical.uses.each do |use| %>
  <tr>
    <td><%= use.chemist %></td>
    <td><%= use.amount %></td>
    <td><%= use.created_at.to_date %></td>
  </tr>
<% end %>
</table>

<h2>Recurring Uses:</h2>
<table>
	<tr>
    <th>Chemist</td>
    <th>Amount</td>
    <th>Periodicity</td>
	  <th>End date</td>
  </tr>
<% @chemical.recurring_uses.each do |recurring_use| %>
  <tr>
    <td><%= recurring_use.chemist %></td>
    <td><%= recurring_use.amount %></td>
    <td><%= recurring_use.periodicity %></td>
    <td><%= recurring_use.end_date %></td>
  </tr>
<% end %>
</table>

<h2>One Time Use:</h2>
<%= form_for([@chemical, @chemical.uses.build]) do |f| %>
  <div class="field">
    <%= f.label :chemist %><br />
    <%= f.text_field :chemist %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Recurring Use:</h2>
<%= form_for([@chemical, @chemical.recurring_uses.build]) do |f| %>
  <div class="field">
    <%= f.label :chemist %><br />
    <%= f.text_field :chemist %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%=f.label :periodicity%><br />
		<%=f.select :periodicity, [['Daily', 'daily'],['Weekly', 'weekly']]%>
	</div>
	<div class="field">
    <%= f.label :end_date, "End date (YYYY-MM-DD)" %><br />
    <%= f.text_field :end_date %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_chemical_path(@chemical) %> |
<%= link_to 'Back', chemicals_path %>